apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "application.fullname" . }}
  labels:
    app: {{ template "application.name" . }}
data:
  MONGO_HOST: {{ .Values.env.MONGO_HOST | quote }}
  MONGO_PORT: {{ .Values.env.MONGO_PORT | quote }}
  MONGO_DB:  {{ .Values.env.MONGO_DB | quote }}
  MONGO_USERNAME: {{ .Values.env.MONGO_USERNAME | quote }}
