apiVersion: v1
kind: Secret
metadata:
  name: {{ template "application.fullname" . }}
  labels:
    app: {{ template "application.name" . }}
data:
  MONGO_PASSWORD: {{ .Values.env.MONGO_PASSWORD | b64enc | quote }}
